---

- hosts: web
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: 
      - apache2
      - libapache2-mod-php
 # - name: install php
 #   apt:
 #     name: libapache2-mod-php
